export const SET_INGREDIENT = 'SET_INGREDIENT';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SIGNED_IN='SIGNED_IN';
export const SET_FAVS='SET_FAVS';
